### ISSUE TITLE
[1.0.0] Metal Former mode resets to Plate Crush periodically

### ISSUE THREAD

**Issue by Renniuq** [LambdaInnovation/AcademyCraft#337] opened 2016-05-15 01:29 UTC
I've been having this issue for a while, and can't seem to narrow down a specific cause. It seems to be something time-based, and it has even happened while processing a stack of items while I had the UI open. This didn't update the GUI, but when I closed and re-opened it, it was in plate crushing instead of etching like before. Someone on the curse page seems to have been having the same problem, so I figured I'd put this up. It isn't whenever you close and open the GUI, and it hasn't actually cut a process off partway. It's only swapped mode right after a process finishes, causing the next to not run due to the wrong mode.

**Comment by WeAthFoLD** [comment] 2016-05-15 03:01
The cause is same with some of the previous metal former errors -- NBT reading/writing. Already fixed in 1.0.1.

**Closed by WeAthFoLD** 2016-05-15 03:01 UTC
Labels: bug, wontfix
