### ISSUE TITLE
[Bug] Using Storm Wings unbinds A-strafe button

### ISSUE THREAD

**Issue by CmdrJane** [LambdaInnovation/AcademyCraft#775] opened 2019-03-23 00:03 UTC
After using Vector Manipulator Storm Wings A-strafe button unbinds. Nothing special in console.

Academy Craft 1.1.1
Minecraft 1.12.2

**Comment by Ruchian** [comment] 2019-03-23 14:18
Duplicate of #712

**Comment by nirvanaxiao6** [comment] 2019-03-31 09:56
Duplicated.

**Closed by nirvanaxiao6** 2019-03-31 09:56 UTC
Labels: bug
